# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d37b5ebf3f11c861a1b811bb7f1227c813218cc668bd84a724b0d8bdeed93cbdf2c457a770d3f60e75a64f05a9c39d0cde96146ee4ea2a4f8e5d700b819c66

test:
  secret_key_base: 6df2805d61a14ce777fcb8c8cb34229478eb0dfbebcb305dda8c30327b50c618d835889f7b3bf0bec32434a5473e70c7a5c8f5c77da6b035a8cb81e59b84412a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
